language: python
python:
  - "2.7"
sudo: false
services:
  - elasticsearch
before_script:
  - mysql -e 'SET @@GLOBAL.wait_timeout=28800'
before_install:
  - pip install flake8
  - flake8 mozillians
  - mysql -e 'create database mozillians character set utf8;'
  - cp mozillians/settings/local.py-travis mozillians/settings/local.py
install:
  - ./peep.sh install -r requirements/dev.txt
  - pip install coverage
script:
  - coverage run --source=mozillians manage.py test
after_success:
  - pip install coveralls
  - coveralls
