db:
  image: mysql:5.5
  environment:
    - MYSQL_DATABASE=mozillians
    - MYSQL_USER=mozillians
    - MYSQL_PASSWORD=mozillians
    - MYSQL_ROOT_PASSWORD=root
es:
  image: barnybug/elasticsearch:1.2.1
broker:
  image: rabbitmq
celery:
  build: .
  volumes:
    - .:/code
  links:
    - db
    - es
    - broker
  command: celery -A mozillians worker -l INFO
  environment:
    - C_FORCE_ROOT=true
web:
  build: .
  ports:
    - "8000:8000"
  volumes:
    - .:/code
  links:
    - db
    - es
    - broker
    - celery
  command: python manage.py runserver 0.0.0.0:8000
